# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'playerui.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(500, 305)
        MainWindow.setMinimumSize(QtCore.QSize(500, 297))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.sldPosition = QtWidgets.QSlider(self.centralwidget)
        self.sldPosition.setGeometry(QtCore.QRect(60, 230, 381, 21))
        self.sldPosition.setOrientation(QtCore.Qt.Horizontal)
        self.sldPosition.setObjectName("sldPosition")
        self.btnPrevious = QtWidgets.QPushButton(self.centralwidget)
        self.btnPrevious.setGeometry(QtCore.QRect(20, 250, 41, 31))
        self.btnPrevious.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/151845-music-player-icons/png/back.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)

        self.btnPrevious.setIcon(icon)
        self.btnPrevious.setIconSize(QtCore.QSize(22, 22))
        self.btnPrevious.setObjectName("btnPrevious")
        self.btnPlay = QtWidgets.QPushButton(self.centralwidget)
        self.btnPlay.setGeometry(QtCore.QRect(60, 250, 41, 31))
        self.btnPlay.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/151845-music-player-icons/png/play-button.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.btnPlay.setIcon(icon1)
        self.btnPlay.setIconSize(QtCore.QSize(22, 22))
        self.btnPlay.setObjectName("btnPlay")
        self.btnPause = QtWidgets.QPushButton(self.centralwidget)
        self.btnPause.setGeometry(QtCore.QRect(100, 250, 41, 31))
        self.btnPause.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icons/151845-music-player-icons/png/pause.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.btnPause.setIcon(icon2)
        self.btnPause.setIconSize(QtCore.QSize(22, 22))
        self.btnPause.setObjectName("btnPause")
        self.btnNext = QtWidgets.QPushButton(self.centralwidget)
        self.btnNext.setGeometry(QtCore.QRect(140, 250, 41, 31))
        self.btnNext.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("icons/151845-music-player-icons/png/next-1.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.btnNext.setIcon(icon3)
        self.btnNext.setIconSize(QtCore.QSize(22, 22))
        self.btnNext.setObjectName("btnNext")
        self.sldVolume = QtWidgets.QSlider(self.centralwidget)
        self.sldVolume.setGeometry(QtCore.QRect(340, 260, 101, 21))
        self.sldVolume.setSliderPosition(50)
        self.sldVolume.setOrientation(QtCore.Qt.Horizontal)
        self.sldVolume.setObjectName("sldVolume")
        self.btnMute = QtWidgets.QPushButton(self.centralwidget)
        self.btnMute.setGeometry(QtCore.QRect(310, 250, 31, 31))
        self.btnMute.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("icons/151845-music-player-icons/png/speaker.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.btnMute.setIcon(icon4)
        self.btnMute.setIconSize(QtCore.QSize(22, 22))
        self.btnMute.setObjectName("btnMute")
        self.lbPosition = QtWidgets.QLabel(self.centralwidget)
        self.lbPosition.setGeometry(QtCore.QRect(0, 230, 51, 20))
        self.lbPosition.setText("")
        self.lbPosition.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbPosition.setObjectName("lbPosition")
        self.lbTitle = QtWidgets.QLabel(self.centralwidget)
        self.lbTitle.setGeometry(QtCore.QRect(260, 180, 231, 20))
        self.lbTitle.setText("")
        self.lbTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.lbTitle.setObjectName("lbTitle")
        self.listPlaylist = QtWidgets.QListView(self.centralwidget)
        self.listPlaylist.setGeometry(QtCore.QRect(10, 10, 241, 211))
        self.listPlaylist.setAcceptDrops(True)
        self.listPlaylist.setProperty("showDropIndicator", True)
        self.listPlaylist.setDragDropMode(QtWidgets.QAbstractItemView.DropOnly)
        self.listPlaylist.setAlternatingRowColors(True)
        self.listPlaylist.setUniformItemSizes(True)
        self.listPlaylist.setObjectName("listPlaylist")
        self.btnAdd = QtWidgets.QPushButton(self.centralwidget)
        self.btnAdd.setGeometry(QtCore.QRect(252, 10, 21, 21))
        self.btnAdd.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("icons/151845-music-player-icons/png/plus.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.btnAdd.setIcon(icon5)
        self.btnAdd.setIconSize(QtCore.QSize(16, 16))
        self.btnAdd.setObjectName("btnAdd")
        self.lbArtist = QtWidgets.QLabel(self.centralwidget)
        self.lbArtist.setGeometry(QtCore.QRect(260, 200, 231, 20))
        self.lbArtist.setText("")
        self.lbArtist.setAlignment(QtCore.Qt.AlignCenter)
        self.lbArtist.setObjectName("lbArtist")
        self.picCover = QtWidgets.QLabel(self.centralwidget)
        self.picCover.setGeometry(QtCore.QRect(290, 10, 170, 170))
        self.picCover.setText("")
        self.picCover.setObjectName("picCover")
        self.lbTotalTime = QtWidgets.QLabel(self.centralwidget)
        self.lbTotalTime.setGeometry(QtCore.QRect(445, 230, 58, 18))
        self.lbTotalTime.setText("")
        self.lbTotalTime.setObjectName("lbTotalTime")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")

        self.btnPrevious.setStyleSheet("border: none")
        self.btnNext.setStyleSheet("border: none")
        self.btnPlay.setStyleSheet("border: none")
        self.btnMute.setStyleSheet("border: none")
        self.btnPause.setStyleSheet("border: none")
        self.btnAdd.setStyleSheet("border: none")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.setAcceptDrops(True)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "qPlayer"))

